# Generated by Django 5.1.1 on 2024-09-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_email'),
    ]

    operations = [
    ]
