# Generated by Django 5.1.1 on 2024-09-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240924_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamreport',
            name='spam_count',
            field=models.IntegerField(default=1),
        ),
    ]
